### PR TITLE
[Fix]: Issue 264 | Anthropic with Title Gen

### LINKED ISSUE #264: Error using Anthropic with Title Gen
### Description

As flagged by @gziolo in https://github.com/WordPress/ai/pull/228#issuecomment-3943514795, there's an error when generating titles with Anthropic (while generating excerpts and summaries work as expected):

Screenshot 2026-02-23 at 10 07 30

Also per https://github.com/WordPress/ai/pull/228#issuecomment-3983159946 the issue exists in the current released version of the plugin and is not an issue in the #228 PR branch (or just in the `develop` branch).

### Step-by-step reproduction instructions

1. Add an Anthropic API key
2. enable title gen
3. attempt to generate a title, see error as noted above

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except AI Experiments plugin.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by TylerB24890**
## What?

Closes #264 

This PR removes the multiple candidates from the Title Generation experiment and makes it return only one. All E2E and unit tests updated accordingly.

## Why?

As described in https://github.com/WordPress/ai/issues/264 -- Anthropic and OpenAI no longer support multiple candidate responses. This PR ensures the title generation logic continues to work even if only one of those models is currently connected.

## How?

Remove all references to candidates within the Title Generation experiment. With the removal of multiple candidates per response, the modal UI has been removed and titles are just inserted into the post directly. Editors can then regenerate the title as needed using the existing toolbar button.

### Use of AI Tools

* **AI Assistance:** Yes
* **Tool(s):** Claude Code (Opus 4.6)
* **Used for:**
    * Outlining everywhere candidates were referenced and used
    * Update E2E and Unit Tests accordingly

## Testing Instructions

1. Ensure the "Title Generation" experiment is enabled.
2. Ensure only an Anthropic connector is active.
3. Navigate to a post and click the "Regenerate" button.
4. Confirm a title is generated and inserted into the post title field.

<a href="https://playground.wordpress.net?blueprint-url=data:application/json,%7B%22preferredVersions%22%3A%7B%22wp%22%3A%22beta%22%7D%2C%22steps%22%3A%5B%7B%22step%22%3A%22installPlugin%22%2C%22pluginZipFile%22%3A%7B%22resource%22%3A%22url%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2FWordPress%2Fai%2Freleases%2Fdownload%2Fci-artifacts%2Fpr-341-5290d7c5064dc81fd5344d07a21d76fd77eb68e8.zip%22%7D%7D%5D%7D" target="_blank" rel="noopener noreferrer">
  Open WordPress Playground Preview
</a>

### CODE REVIEW

File: includes/Abilities/Title_Generation/Title_Generation.php [hunk 1]
```diff
@@ -229,10 +211,9 @@ protected function meta(): array {
 	 *
 	 * @param string $content The content to generate title suggestions for.
 	 * @param string|array<string, string> $context Additional context to use.
-	 * @param int $candidates The number of titles to generate.
-	 * @return array<string>|\WP_Error The generated titles, or a WP_Error if there was an error.
+	 * @return array<string>|\WP_Error The generated title wrapped in an array, or a WP_Error if there was an error.
 	 */
-	protected function generate_titles( string $content, $context, int $candidates = 1 ) {
+	protected function generate_titles( string $content, $context ) {
```
Comment (dkotter) [inline includes/Abilities/Title_Generation/Title_Generation.php]: What are your thoughts on taking this further? Right now this method is still named `generate_titles` even though it only generates a single title. Also, we return an array that contains a single title.

I'd suggest at least updating this method and we could think about changing our output schema so we only return a single item instead of an array that contains a single item (which also would simplify our JS logic). That is technically a breaking change though I'm not concerned with that, since this is still marked as an experiment. But open to opinions here

File: src/experiments/title-generation/components/TitleToolbar.tsx [hunk 2]
```diff
@@ -189,72 +89,39 @@ export default function TitleToolbar(): JSX.Element | null {
...
 
 		try {
-			const generatedTitles = await generateTitles(
+			const generatedTitle = await generateTitle(
 				postId as number,
 				content
 			);
-			setTitles( generatedTitles );
-			openModal();
+			editPost( { title: generatedTitle } );
```
Comment (dkotter) [inline src/experiments/title-generation/components/TitleToolbar.tsx:93]: I know we are purposely changing the approach in this PR to automatically set the title instead of showing that in a modal. Wondering if that's worth a discussion first? I'm fine with it but noting it is a change to how it currently works, where we give the user a chance to review, edit and accept the title before using it

Comment (TylerB24890) [reply src/experiments/title-generation/components/TitleToolbar.tsx:93]: I had that thought too. I guess if they didn't like the title they could just regenerate it or refresh the page to revert it, but it does feel a little out-of-place since almost everything else gives you the opportunity to review before accepting.

Should we implement a popover UI that shows the suggested title with an _Apply_ button or something? That should be pretty simple to implement.

File: includes/Abilities/Title_Generation/Title_Generation.php (hunk 1 above)
Comment (TylerB24890) [reply includes/Abilities/Title_Generation/Title_Generation.php]: I've applied all the necessary changes to reflect a single title being returned. Updated all function names, tests and removed the array from the response.

Comment (TylerB24890) [reply includes/Abilities/Title_Generation/Title_Generation.php]: Not sure why the coverage check is failing here. I've added several new unit tests to try and offset it, but can't seem to get the patch coverage to pass 🤔

Comment (dkotter) [reply includes/Abilities/Title_Generation/Title_Generation.php]: Yeah it's finicky. As long as the changes in a PR have tests I don't pay much attention to that coverage check so you're good here

File: src/experiments/title-generation/components/TitleToolbar.tsx [hunk 3]
```diff
@@ -25,129 +17,42 @@ import { store as noticesStore } from '@wordpress/notices';
...
+	) {
+		return response.title;
+	}
 
-			return [];
-		} )
-		.catch( ( error ) => {
-			throw new Error( `Error generating titles: ${ error.message }` );
-		} );
+	throw new Error( __( 'No title suggestion was generated.', 'ai' ) );
```
Comment (dkotter) [inline src/experiments/title-generation/components/TitleToolbar.tsx:55]: This isn't working now, I get the following when an error happens:

Error notice when title generation fails

In addition, we'll want to ensure we still render the error message that comes from the server as this will provide more details to the user when something is wrong (for example, if they don't have a Provider configured that supports text generation)

File: src/experiments/title-generation/components/TitleToolbar.tsx (hunk 2 above)
Comment (dkotter) [reply src/experiments/title-generation/components/TitleToolbar.tsx:93]: Honestly I think this fine for now. If we get feedback wanting to see the result before it's applied we can think about this again but for now, this works for me

**Review by dkotter — CHANGES_REQUESTED** [review]

File: src/experiments/title-generation/components/TitleToolbar.tsx (hunk 3 above)
Comment (TylerB24890) [reply src/experiments/title-generation/components/TitleToolbar.tsx:55]: Error message display should be resolved. Please let me know if you're still experiencing issues.

**Review by dkotter — APPROVED** [review]
