### PR TITLE
Fix duplicate "Settings saved" notice on settings page

### LINKED ISSUE #128: "Settings saved" message appears twice
### Description

While changing and saving any changes on AI Experiments page under admin, it shows the success message as "Settings saved." twice. This should appear only once.

### Step-by-step reproduction instructions

1. Go to "Admin > Settings > AI Experiments" Page
2. Change / Don't change any settings on this page
3. Click "Save Changes"

### Screenshots, screen recording, code snippet

Image

### Environment info

- WordPress Version: 6.8.3

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except AI Experiments plugin.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by aslamdoctor**
## What?

Closes 
#128 

Fix duplicate settings notice by specifying option group in `settings_errors()`

## Why?

While changing and saving any changes on AI Experiments page under admin, it was showing the success message as "Settings saved." twice. This PR fixes it to appear only once.

## How?

Specified option group under `settings_error()` method as below
```
settings_errors('ai_experiments');
```

## Testing Instructions

1. Go to "Admin > Settings > AI Experiments" Page
2. Change / Don't change any settings on this page
3. Click "Save Changes"

## Screenshots or screencast 

|Before|After|
|-|-|
|
image|image|

### CODE REVIEW

**Review by mindctrl — APPROVED** [review]
Works as expected.

File: includes/Settings/Settings_Page.php [hunk 1]
```diff
@@ -150,7 +150,7 @@ public function render_page(): void {
 			}
 			?>
 
-			<?php settings_errors(); ?>
+			<?php settings_errors( 'ai_experiments' ); ?>
```
Comment (dkotter) [inline includes/Settings/Settings_Page.php:153]: This is my mistake coming out of #100. Originally I was using this to display errors logged using `add_settings_error` but then removed that as it wasn't needed, but forgot to remove this. We could just remove this line for now but I'm also fine leaving this in case we do have settings errors we want to display in the future

**Review by dkotter — APPROVED** [review]
